### ISSUE TITLE
Error installing package when __version__ is instrumented

### ISSUE THREAD

**Issue by junholee6a** [sola-st/DynaPyt#29]
Trying to run DynaPyt on the [FastAPI](https://github.com/tiangolo/fastapi) project, with TraceAll analysis using the `experiment.sh` script. I get the following error when the script installs fastapi after instrumentation:
![image](https://github.com/sola-st/DynaPyt/assets/53921230/3e3f8402-5e26-45b6-b0a1-ff644ef76a47)

Key line is `ValueError: Error getting the version from source 'regex': unable to parse the version from the file: fastapi/__init__.py`. [It seems like pip parses `fastapi/__init__.py` to find the package's version number](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/), and is unable to find the version number here.

The file `fastapi/__init__.py` looks like this after instrumentation:
![image](https://github.com/sola-st/DynaPyt/assets/53921230/4f2819b2-0ec7-4a17-b993-0071c8bbd2ff)

Moving the `__version__` declaration to outside of the try-catch block, and replacing the `_write_` hook with `"0.96.0"`, makes the error go away when re-running the script (just moving it to outside the try-catch block or just replacing the `_write_` hook with `"0.96.0"` is not sufficient; you need to do both):
<img width="1126" alt="Screenshot 2023-06-16 at 11 27 39 AM" src="https://github.com/sola-st/DynaPyt/assets/53921230/af05169b-ac89-46c4-93b6-409380c26fbf">

Making the change above makes installation and tests run correctly. Is this worth changing the instrumentation code so that variables with the name `__version__` are never instrumented?

**Comment by junholee6a** [comment]
Ran into the same issue with beautifulsoup. Perhaps other variables such as `__author_`, `__copyright__`, `__license__`, and `__all__` should also be considered?

**Comment by junholee6a** [comment]
It seems like the `_write_` hook [has an exception such that variables called `__version__` in `__init__.py` files are not instrumented](https://github.com/sola-st/DynaPyt/blob/63dbd6bffbfaa0f711bc4d36e47bbd50c022d3f2/src/dynapyt/instrument/CodeInstrumenter.py#LL863C16-L863C16). However, no such exception applies for the `_str_` hook or the try-catch hook

**Comment by AryazE** [comment]
I think [this commit](https://github.com/sola-st/DynaPyt/commit/15a804a6f3ba206986b851db38ee2a2d019041ae) should not have this problem anymore.
Feel free to reopen the issue if it is not resolved or if you find another way it can fail.
