### ISSUE TITLE
`__file__` in the instrument target file evaluates to `...dynapyt/run_analysis.py`

### ISSUE THREAD

**Issue by k1832** [sola-st/DynaPyt#38]
Since the instrumented target file is run with `exec(open(abspath(entry)).read(), globals())` (the code is [here](https://github.com/sola-st/DynaPyt/blob/211e56924b521469983903cf96d14002aedcfd4f/src/dynapyt/run_analysis.py#L47)) from `...dynapyt/run_analysis.py`, any `__file__` in the target file evaluates to `...dynapyt/run_analysis.py`. This changes the behavior of the target file.

Minimum steps to reproduce this.
1. Create `tmp.py` with the content `print(__file__)`
2. Insert instrumentation in `tmp.py`
3. Run analysis

Expected behavior: the script prints `...../tmp.py`
Actual: it prints `......./dynapyt/run_analysis.py`

**Comment by k1832** [comment]
One possible (quick) fix for this could be replace
```
exec(open(abspath(entry)).read(), globals())
```

with 

```
entry_full_path = abspath(entry)
exec(open(entry_full_path).read().replace("__file__", f"\"{entry_full_path}\""), globals())
```

**Comment by AryazE** [comment]
Thanks for raising this issue.
Feel free to reopen it if the fix does not work.
