### ISSUE TITLE
More `_enter_if` than `_exit_if` function calls using `if (...) elif`

### ISSUE THREAD

**Issue by berbjs** [sola-st/DynaPyt#47]
Given the following program:
```python
y = 101
if y > 101:
    y -= 1
elif y <= 100:
    y *= 2
```

DynaPyt (v 1.7.0) generates the following instrumented code (slightly abridged for readability):
```python
y = _rt._write_(_dynapyt_ast_, 1, _rt._int_(_dynapyt_ast_, 0, 101), [lambda: y])
if _rt._enter_if_(_dynapyt_ast_, 13, _rt._comp_op_(_dynapyt_ast_, 4, _rt._read_(_dynapyt_ast_, 2, lambda: y), [(1, _rt._int_(_dynapyt_ast_, 3, 101))])):
    y -= _rt._aug_assign_(_dynapyt_ast_, 6, lambda: y, 12, _rt._int_(_dynapyt_ast_, 5, 1))
    _rt._exit_if_(_dynapyt_ast_, 13)
elif _rt._enter_if_(_dynapyt_ast_, 12, _rt._comp_op_(_dynapyt_ast_, 9, _rt._read_(_dynapyt_ast_, 7, lambda: y), [(6, _rt._int_(_dynapyt_ast_, 8, 100))])):
    y *= _rt._aug_assign_(_dynapyt_ast_, 11, lambda: y, 9, _rt._int_(_dynapyt_ast_, 10, 2))
    _rt._exit_if_(_dynapyt_ast_, 12)
else:
    _rt._exit_if_(_dynapyt_ast_, 12)
```

In this case, `_rt._enter_if` is called for both IIDs 12 and 13 (in lines 2 + 5 of the instrumented code). However, `_rt._exit_if()` is never called for the IID 13 and instead only for IID 12 as the else branch is executed.
Thus, in case the if branch is not used, `_enter_if` is called more often than `_exit_if`, i.e. there are some `if` statements that appear to be entered but never exited. Is this the intended behavior?

**Comment by AryazE** [comment]
Each `if` or `elif` block has its own `_exit_if_`. So if a block is entered and not `break` happens, the corresponding `_exit_if_` is also called.
However, for the `else` block, the `_exit_if_` of the last `if` or `elif` block is called. This way the `enter_if` hook of `elif y <= 100:` is called first with condition value `False`, and then the `exit_if` is called with the same IID after the else block (empty block in this case) was executed.

**Comment by berbjs** [comment]
I do understand that this is the current behavior. I personally however would not expect this behavior as I think an `elif` should be semantically equivalent to an `else` with a nested `if`, in which case `_exit_if` would be called twice when not executing the `if` case:
```python
y = 101
if y > 101:
    y -= 1
else:
    if y <= 100:
        y *= 2
```
leading to
```python
y = _rt._write_(_dynapyt_ast_, 0, 101, [lambda: y])
if _rt._enter_if_(_dynapyt_ast_, 6, _rt._read_(_dynapyt_ast_, 1, lambda: y) > 101):
    y -= _rt._aug_assign_(_dynapyt_ast_, 2, lambda: y, 12, 1)
    _rt._exit_if_(_dynapyt_ast_, 6)
else:
    if _rt._enter_if_(_dynapyt_ast_, 5, _rt._read_(_dynapyt_ast_, 3, lambda: y) <= 100):
        y *= _rt._aug_assign_(_dynapyt_ast_, 4, lambda: y, 9, 2)
        _rt._exit_if_(_dynapyt_ast_, 5)
    else:
        _rt._exit_if_(_dynapyt_ast_, 5)
    _rt._exit_if_(_dynapyt_ast_, 6)
```
I can however understand that calling `_exit_if` twice in case the `if` is not executed could also be confusing, so I can also see a reason for keeping the current behavior, so feel free to close the issue if this is the chosen behavior.

**Comment by AryazE** [comment]
That's a good point.
However, I cannot think of an analysis that would become much easier to implement with having the exits for all enters. If you do, please let me know.
In addition, I think having the ability to distinct `elif`s and nested `if`s might be useful.
I will keep this issue open to have more time to consider it.
